### DISCUSSION TITLE
Is `pygments` needed in `hugo,yaml`?

### DISCUSSION THREAD

**Discussion by SayakMukhopadhyay** [google/docsy#2150] [Q&A] [answered]
I have noticed that the docsy userguide still uses the various `pygments` properties in its config (see https://github.com/google/docsy/blob/main/userguide/hugo.yaml#L7-L10). 

```yaml
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango
```

Are these properties needed to be present at all? Removing them doesn't seem to impact anything but I want to double check.
