### ISSUE TITLE
How to use taxonomies with multiple words?

### ISSUE THREAD

**Issue by at055612** [google/docsy#1002]
I have two custom taxonomies that are both made of two words.  It is not clear how to configure these multi word taxonomies.
If I use lower_snake_case `object_types` then it works fine, but if I use lowerCamelCase `schemaActions` (which is more consistent with the rest of the configuration and front matter) it doesn't show the cloud for "Schema Actions" (see screen shots below).  Is this my mistake or a bug?

My config is
```toml
[taxonomies]
tag = "tags"
object_type = "object_types"
schemaAction = "schemaActions"

[params.taxonomy]
taxonomyCloud = ["tags", "object_types", "schemaActions"] 
taxonomyCloudTitle = ["Tag Cloud", "Object Types", "Schema Actions"] 
taxonomyPageHeader = ["tags", "object_types", "schemaActions"] 
```

Front matter is
```yaml
---
schemaActions:
  - xyz
object_types:
  - def
title: "Glossary"
linkTitle: "Glossary"
weight: 80
date: 2022-02-16
tags: 
  - xxx
  - yyy
  - zzz
description: >
  Glossary of common words and terms used in Stroom.
---
```

![image](https://user-images.githubusercontent.com/22818309/167108159-fb578997-b15d-4415-88b0-f710251ce5b4.png)

![image](https://user-images.githubusercontent.com/22818309/167108346-79fb2b1a-9bda-47c9-bf4d-625df5fc4322.png)

If I change `schemaActions?` to `schema_actions?` the cloud is shown:

![image](https://user-images.githubusercontent.com/22818309/167108798-10d2875a-f154-4993-86a9-266ba96921c8.png)
