### ISSUE TITLE
[Bug report] GitHub links do not respect config

### ISSUE THREAD

**Issue by stephanlachnit** [google/docsy#1046]
Consider the following config:

```toml
contentDir = "content2"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
```

This means the main content is in the `content2/` folder. But [layouts/partials/page-meta-links.html](https://github.com/google/docsy/pull/1045/files#diff-f4d9e149cd577180bf360992c9474342dc2fe345c105c05e61b080f769e02281) will guess this as `content/en`, because is does not respect either the `contentDir` and `defaultContentLanguageInSubdir` setting.
