### ISSUE TITLE
Search icon (magnifying glass) is not rendered properly in FF

### ISSUE THREAD

**Issue by sophokles73** [google/docsy#1256]
The search input field's magnifying glass is not rendered as the magnifying glass icon but as the literal text `fl` in my browser. See attached screenshot

![image](https://user-images.githubusercontent.com/5682135/194233797-30ef321c-f388-49b6-97ac-b9995cd6e767.png)

This seems to be due to the order in which the font-family is defined for the `.td-search-input` class in `_search.scss`
```css
.td-search-input {
    ...
    font-family: $font-family-base, $font-awesome-font-name;
}
```

where the font awesome font is added to the end of the list but one of the fonts before font awesome in the list already contains a value for the `&#xf002;` entity.

---

**Edit** (@chalin):

- [x] Fix for regular search - #1247 
- [ ] Fix for offline search
