### ISSUE TITLE
Local search not working with Netlify

### ISSUE THREAD

**Issue by masgustavos** [google/docsy#1274]
Hi folks! Thanks for the project.

Here's my issue: In local development (using docker-compose) I'm able to use the offline search feature, with this config snippet:

```toml
# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "d72aa9b2712488qc3"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true
offlineSearchSummaryLength = 200
offlineSearchMaxResults = 50
```

However, in Netlify's deployment I see the search bar and I'm able to write in it, but get no response from the search (after pressing "enter"). This behavior is true for both side and nav bars.

Here is it working locally:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/24419975/195362690-8ffa4702-947c-4cb5-aa3a-58840e61d8d5.png">

I've setup Netlify with the `cd themes/docsy && git submodule update -f --init && cd ../.. && hugo` build command as stated in [the docs](https://www.docsy.dev/docs/deployment/#deployment-with-netlify).

Here's the deployed site in case you want to take a loot at it: https://masgustavos.com/docs/git/how-to-use-multiple-ssh-keys/
