### ISSUE TITLE
After migrating to Hugo module, can no longer load FontAwesome files

### ISSUE THREAD

**Issue by EspadaV8** [google/docsy#1285]
I have followed the guide on the Docsy site (<https://www.docsy.dev/docs/updating/convert-site-to-module/>) to switch from a git submodule to a Hugo module, and most things seem to be working, but now I get a 404 when attempting to load any of the FontAwesome files. Checking the `mod graph` and it looks correct to me

```shell
> docker compose exec local hugo mod graph
gitlab.com/xxx/yyy github.com/google/docsy@v0.5.0
gitlab.com/xxx/yyy github.com/google/docsy/dependencies@v0.5.0
github.com/google/docsy/dependencies@v0.5.0 github.com/twbs/bootstrap@v4.6.1+incompatible
github.com/google/docsy/dependencies@v0.5.0 github.com/FortAwesome/Font-Awesome@v0.0.0-20210804190922-7d3d774145ac
```

The page is just a generic 404 page when attempting to view the file

![image](https://user-images.githubusercontent.com/115825/196064030-0df88bf9-8521-4d21-8b48-04bd4c3a8795.png)

I have commented out the `theme` line in `config.toml` and added the `module` information in

```toml
[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  # [module.hugoVersion]
  #   extended = true
  #   min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    # disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    # disable = false
```

I think the only major difference is that I'm running Hugo locally via a docker-compose file. Not sure if there is a change there that's needed.
