### ISSUE TITLE
Close button in search-input not selectable or visible in html

### ISSUE THREAD

**Issue by avihr** [google/docsy#1630]
Close button in search-input not selectable or visible in HTML
[search-input.html](https://github.com/google/docsy/blob/main/layouts/partials/search-input.html)
![image](https://github.com/google/docsy/assets/74286364/7cb08c7d-12a7-4aba-b139-59e72622f465)

**Comment by tekezo** [comment]
It's visible when text is entered.

<img width="1600" alt="Screenshot 2023-07-24 at 20 38 09" src="https://github.com/google/docsy/assets/659178/62ad2f89-f06a-4ee7-b9aa-eef69b85ec15">

**Comment by avihr** [comment]
> It's visible when text is entered.
> 
> <img alt="Screenshot 2023-07-24 at 20 38 09" width="1600" src="https://user-images.githubusercontent.com/659178/255578501-62ad2f89-f06a-4ee7-b9aa-eef69b85ec15.png">

not in UI, in HTML code

**Comment by tekezo** [comment]
It's browser native component of input[type=search]. 
If you want to change the style, use `-webkit-search-cancel-button` as follows.

```scss
input[type="search"]::-webkit-search-cancel-button {
  position: relative;
  right: 20px;

  -webkit-appearance: none;
  height: 20px;
  width: 20px;
  border-radius: 10px;
  background: red;
}
```

https://stackoverflow.com/questions/20804016/editing-input-type-search-pseudo-element-button-x
