### ISSUE TITLE
taxonomies multi-language bug at page header

### ISSUE THREAD

**Issue by BrentHuang** [google/docsy#2077]
### Environment

- [x] Version of Docsy you are using: v0.10.0
- [ ] How are you using Docsy? As a:
  - [x] Hugo module
  - [ ] NPM module
  - [ ] Git submodule
  - [ ] Other:
- [x] Version of Hugo you are using (output of `hugo version`): v0.134.1
- [ ] OS:
  - [x] Linux (WSL)
  - [ ] macOS
  - [ ] Windows
  - [ ] Other:

### Problem

![image](https://github.com/user-attachments/assets/67a6e163-61c4-4a22-903c-723abed0dcce)

config in hugo.toml

```toml
# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
# taxonomyCloudTitle = ["Tag Cloud", "Categories"]
taxonomyCloudTitle = ["标签", "分类"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]
```

**Comment by deining** [comment]
The issue title is misleading: this is not a bug, this can be solved via correct configuration parameters:

> config in hugo.toml
...

Use this configuration instead:

```toml
# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
标签 = "Plural form of 标签"
分类 = "Plural form of 分类"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
# taxonomyCloudTitle = ["Tag Cloud", "Categories"]
taxonomyCloudTitle = ["标签", "分类"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["标签", "分类"]
```

Then you should be see the page headers as desired.
Does this resolve your issue?
