### ISSUE TITLE
duplicated paths in menu when using baseURL with path

### ISSUE THREAD

**Issue by tverbeke** [google/docsy#280]
When using a `baseURL` with a path after the host name e.g. `baseURL: http://localhost/infra` all menu items in the main menu will have duplicated paths e.g. `http://localhost:1313/infra/infra/about/` for a menu item defined as 

```
main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
```

This is hugo extended version 0.71.1 with autoprefixer 9.8 and postcsscli 7.0.0 using YAML based config in `config/_default/config.yaml` and `menu.yaml` respectively using docsy https://github.com/google/docsy/commit/053672c24cf51417c300f8ea5d32db545340746d on Ubuntu 18.04 LTS. Let me know if more information is needed to reproduce the issue and many thanks in advance for your help!
