### ISSUE TITLE
Toggle expand/collapse for left-side menus/TOC

### ISSUE THREAD

**Issue by prdsoftware** [google/docsy#342]
Firstly, love the theme - thanks for the hard work that's gone into this.

Is it possible to expand/collapse the menu structure on the left?

While I'm at it, is it possible to reduce the font-size a point or 2 for the left-menu structure.  Many titles are wrapping over 2 lines, but with a font size slightly smaller, this wouldn't happen - at least for the words I'm using - is this a CSS thing?

**Comment by gwatts** [comment]
@prdsoftware to change whether the left menu is expanded/compact, in  `config.toml` you can set the `sidebar_menu_compact` parameter (see https://www.docsy.dev/docs/adding-content/navigation/#section-menu ):
```toml
 [params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
```

You can also control what appears in that left-menu on a per page basis, so you can choose a shorter title that fits better there by setting `linkTitle` in the page matter at the top of each page (see also https://www.docsy.dev/docs/adding-content/navigation/ )

```yaml
---
title: "My nice long page title"
linkTitle: "Short title"
weight: 10
---
```

If you want to make the font size smaller for that nav, try this in your project's `assets/sccs/_variables_project.scss`  file (see also https://www.docsy.dev/docs/adding-content/lookandfeel/)
```css
.td-sidebar-nav {
  font-size: 0.8em !important;
}
```

(there might be a better way of overriding that css; it's not my strong suit ;-) )
