### ISSUE TITLE
Copy only necessary items from the code block

### ISSUE THREAD

**Issue by iamrajiv** [google/docsy#818]
## Description

When I use the copy button to copy the codes then unnecessary characters are also copied like I want to copy the below code but do not want the `$` character to be copied. I want to copy only `echo "Hello World"` after clicking the copy button.

```shell
$ echo "Hello World"
```

**Comment by iamrajiv** [comment]
@LisaFC

**Comment by chalin** [comment]
This is only when Prism is used, correct?

I've been able to fix this in other projects by adding [`user-select: none`][us] to the prompt class(es). Might you be willing to give that a try?

[us]: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by iamrajiv** [comment]
Yeah sure @chalin. Can you send me the link to the project where you have fixed this issue? also, what does prompt class(es) mean?

**Comment by chalin** [comment]
This was fixed in the Flutter website. For example, see the code blocks on this page: https://docs.flutter.dev/get-started/install/macos#get-sdk

> what does prompt class(es) mean?

I mean the CSS classes uses to style prompts in code blocks, such as the `gp` class in the case of the Flutter pages:

```html
<span class="gp">$</span>
```

**Comment by chalin** [comment]
For the record, the folks at Stripe use CSS `:before` to insert prompts. For example, see https://stripe.com/docs/api/authentication:

> ![image](https://user-images.githubusercontent.com/4140793/151223885-9fd6067f-20a5-452e-bba3-0b162cd769a0.png)

That probably works best when there's a single command though.

**Comment by at055612** [comment]
Prism has a command-line plugin https://prismjs.com/plugins/command-line/ that adds a prompt for you which is not user selectable.  You just need to build a new pair of `prism.{css,js}` files with the command-line plugin added in, as described [here](https://www.docsy.dev/docs/adding-content/lookandfeel/#code-highlighting-with-prism)

I have made my own shortcode for it like so
```html
<!-- 
{{/*
Short code to add command line input/output
Usage:
command-line username hostname language
username - The username to appear in the prompt, defaults to 'user'
hostname - The hostname to appear in the prompt, defaults to 'localhost'
language - The language of the content, defaults to bash

Prefix lines with '(out)' and it will render them as output lines

See https://prismjs.com/plugins/command-line/

e.g.:
{{% command-line "jdoe" "bigserver" %}}
echo "hello world"
(out) class
id
(out) uid=1000(jdoe) gid=1000(jdoe)
{{% /command-line %}}

*/}}
-->

{{ $user := .Get 0 | default "user" }}
{{ $host := .Get 1 | default "localhost" }}
{{ $language := .Get 2 | default "bash" }}

<div class="code-toolbar">
  <pre class="command-line language-{{ $language }}" data-user="{{ $user }}" data-host="{{ $host }}" data-filter-output="(out)">
  {{- with (.Inner | default "" ) -}}
    <code>{{- trim ( . | default "" ) "\n" -}}</code>
  {{- end -}}
  </pre>
</div>
```

e.g. in your markdown content
```
{{< command-line "david" "wopr" >}}
echo "hello world"
(out)hello world
id
(out)uid=1000(david) gid=1000(david)
{{</ command-line >}}
```

I have added this CSS to stop the output lines being selectable and to tweak the look a bit.

```css
// Font size is too big in the code blocks
pre[class*=language-] {
  font-size: small !important;
}

code[class*=language-] > span:not(.command-line-prompt) {
  user-select: initial;
}

// Shell output lines
.command-line code[class*=language-]:not(span) {
  // Stop them being selectable so the user can just copy the commands
  user-select: none;

  // Make the output lines distinct from the commands
  color: #999;
}
```

On my site it looks like:

![image](https://user-images.githubusercontent.com/22818309/151578292-88aa4fe2-e006-4041-a29a-cb23dae24cec.png)

The snag with this is that the prism copy plugin seems to be broken by the command line plugin.  Need to figure out why they are conflicting.    Also now the content is inside a shortcode rather than a fenced block I lose the syntax highlighting when editing it in vim but that's my problem not the user's.
