### ISSUE TITLE
Feature request: Numbered headings

### ISSUE THREAD

**Issue by at055612** [google/docsy#843]
I found that there is not enough difference in the styling of the headings to make it obvious where in the heading tree you are.  On my site I have added numbered headings (and numbered TOC links).  This makes it much clearer what level a heading is at and where you are in the document, in my opinion.

Also, when printing a section that has child sections this results in a `h1` for each section regardless of the level it is at.  You have addressed this by numbering all `h1`s in the print view but all lower headings are not numbered which is a bit inconsistent.  I have changed this to number all the lower headings based on their parent h1 level.

See this example of:
![image](https://user-images.githubusercontent.com/22818309/149987123-2691c2df-f4ce-491d-8f55-633a2045f558.png)

And when seen in the _print entire section_ view for an ancestor section:
![image](https://user-images.githubusercontent.com/22818309/149987473-0eb9916a-9668-4313-a0d1-22c9a70ee837.png)

This may not be to everybody's taste, but if you feel it would improve the docsy theme then I can raise a PR.  Not sure whether it would be possible to make it toggleable or not.

**Comment by LisaFC** [comment]
I don't think it's something that all sites will want to use by default (and a lot of sites would only use numbered headings for ordered procedures), but if you want to add a toggleable version, go for it

**Comment by LisaFC** [comment]
Sorry, just noticed you asked if it *could* be toggleable - I think the easiest thing to do would be to show users how to add the relevant styles for numbered headings to their `_styles_project.scss`?

**Comment by at055612** [comment]
No problem.  It is a bit of an opinionated change and not everyone's cup of tea.

For anyone that finds this issue and wants to know how then this is what you need to add to `assets/scss/_styles_project.scss`.
This was adapted from https://codingnconcepts.com/hugo/auto-number-headings-hugo/

```scss
:root {
  // When printing a whole section that contains multiple pages, each page has a h1
  // so you end up with multiple nested h1s each with h2+ under them.
  // layout/partials/print/content.html adds numbering for all the h1s but also
  // sets the base number for the h1 into this variable so we can use it to
  // number all the h2+ headings.
  --base-section-num: "";
}

// reset counter for a heading level when its parent level is encountered */
body {counter-reset: h2}
h1 {counter-reset: h2}
h2 {counter-reset: h3}
h3 {counter-reset: h4}
h4 {counter-reset: h5}
h5 {counter-reset: h6}

// prepend the counter value before the heading
h2[id]::before {
  display: inline;
  visibility: visible;
  counter-increment: h2; 
  content: var(--base-section-num,"") counter(h2) " ";
}

h3[id]::before {
  display: inline;
  visibility: visible;
  counter-increment: h3; 
  content: var(--base-section-num,"") counter(h2) "." counter(h3) " ";
}

h4[id]::before {
  display: inline;
  visibility: visible;
  counter-increment: h4; 
  content: var(--base-section-num,"") counter(h2) "." counter(h3) "." counter(h4) " ";
}

h5[id]::before {
  display: inline;
  visibility: visible;
  counter-increment: h5; 
  content: var(--base-section-num,"") counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) " ";
}

h6[id]::before {
  display: inline;
  visibility: visible;
  counter-increment: h6; 
  content: var(--base-section-num,"") counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) " ";
}

// Reset the counter for the right hand TOC items
.td-toc ul { 
  counter-reset: item ;
}

.td-toc li a:before { 
  content: counters(item, ".") " "; 
  counter-increment: item ;
}
```

To get the headings to work in the print view you need to override one of the docsy partials with your own `layouts/partials/print/content.html`
```html
<!--
  This is a copy of themes/docsy/layouts/partials/print/content.html
  that just adds the base-section-num style variable which allows us
  to use it as a prefix for h2+ heading numbering on each page.
-->
{{ $tpl := printf "print/content-%s.html" .Page.Type }}

{{ if templates.Exists (printf "partials/%s" $tpl) }}
  {{ partial $tpl . }}
{{ else -}}
{{ $break := cond .DoPageBreak "page-break-before: always" "" -}}
<div class="td-content" style="--base-section-num: '{{ .PageNum }}.'; {{ $break }}">
    {{ $break := cond .DoPageBreak "page-break-before: always" "" }}
  <h1 id="pg-{{ .Page.File.UniqueID }}">{{ .PageNum }} - {{ .Page.Title }}</h1>
    {{ with .Page.Params.description }}<div class="lead">{{ . | markdownify }}</div>{{ end }}
	{{ .Page.Content }}
</div>
{{ end }}
```
