### ISSUE TITLE
Error building site: TOCSS: failed to transform "scss/main.scss" ... File to import not found or unreadable: vendor/rfs.

### ISSUE THREAD

**Issue by bruxisma** [google/docsy#844]
Hello,

Was excited to see that there were commits showing that docsy supported hugo modules now, however in practice it would seem this is not the case?

With a go.sum file of 

```
github.com/FortAwesome/Font-Awesome v4.7.0+incompatible h1:3trjm7NtX5NXlju1AxSWSzedDMq2hsfH78Qtqrc8EgY=
github.com/FortAwesome/Font-Awesome v4.7.0+incompatible/go.mod h1:IUgezN/MFpCDIlFezw3L8j83oeiIuYoj28Miwr/KUYo=
github.com/google/docsy v0.0.0-20220118162949-b6af3699c65d h1:oD8pf1W/cN6SLN0pUPKt+M3JBZ3iwJGmbJRZ3+yavYs=
github.com/google/docsy v0.0.0-20220118162949-b6af3699c65d/go.mod h1:IRAIgh4ZXxhfPcTDw/XesY+rDcEE/O2khD04Fh2G5o8=
github.com/twbs/bootstrap v4.6.1+incompatible h1:75PsBfPU1SS65ag0Z3Cq6JNXVAfUNfB0oCLHh9k9Fu8=
github.com/twbs/bootstrap v4.6.1+incompatible/go.mod h1:fZTSrkpSf0/HkL0IIJzvVspTt1r9zuf7XlZau8kpcY0=
```

I get the following error when running `hugo` under 0.92 extended

```console
Start building sites …
hugo v0.92.0-B3549403+extended darwin/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "/var/folders/8w/c90mj2dn6sq0jqykj502nbsh0000gq/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/twbs/bootstrap@v4.6.1+incompatible/scss/_mixins.scss", line 6, col 1: File to import not found or unreadable: vendor/rfs.
```

Having looked at the original PR, it seems the _rfs file was added, as it is generated as part of the bootstrap build process, but is not part of the merge into the default branch. Git submodules are *not* an option for this project (they're banned), so what can I do to get this to work?

I'm already using some mounting recommendations I found in other issues from a few days ago and these do not work as well.

My config.toml is:

```toml
baseURL = "/"
enableEmoji = true
footnoteReturnLinkContents = "↩"
languageCode = "en-us"
title = "My Docsy Website"
disableHugoGeneratorInject = true

[module.hugoVersion]
extended = true
min = "0.90.0"

[[module.imports]]
#disable = true
path = "github.com/FortAwesome/Font-Awesome"
mounts = [{ source = "scss", target = "assets/vendor/Font-Awesome/scss" }]
[[module.imports]]
#disable = true
path = "github.com/twbs/bootstrap"
mounts = [{ source = "scss", target = "assets/vendor/bootstrap/scss" }]

[[module.imports]]
path = "github.com/google/docsy"
```

Note: With or without the manual `module.imports` mounting, I get the same error. Any help on this would be appreciated.
