### ISSUE TITLE
Version drop-down causing offline search box not to display

### ISSUE THREAD

**Issue by spacefan** [google/docsy#976]
When i set versioning like this:

```toml
version_menu = "Release"

# Add your release versions here
[[params.versions]]
  version = "master"
  url = "https://master.kubeflow.org"
[[params.versions]]
  version = "v0.2"
  url = "https://v0-2.kubeflow.org"
[[params.versions]]
  version = "v0.3"
  url = "https://v0-3.kubeflow.org"
```

the search menu dispeared. It's a bug?

Reproduce step:
- Install [docsy-example](https://github.com/google/docsy-example)
- Add release versions under `version_menu = "Release"`
- Select local search engine:
  ```toml
  # Google Custom Search Engine ID. Remove or comment out to disable search.
  #gcs_engine_id = "011217106833237091527:la2vtv2emlw"
  
  # Enable Algolia DocSearch
  algolia_docsearch = false

  #Enable offline search with Lunr.js
  offlineSearch = true
  offlineSearchSummaryLength = 70
  offlineSearchMaxResults = 10
  ```
- hugo server
